# Generated by Django 5.1.1 on 2024-10-22 20:48

import backend.image_blob.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('img_url', models.ImageField(upload_to=backend.image_blob.models.get_upload_path)),
                ('description', models.TextField(default='none', max_length=255)),
                ('name', models.CharField(default='Unknown image', max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.CharField(default='Unknown size', max_length=100)),
                ('filetype', models.CharField(default='Unknown file type', max_length=100)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.userprofile')),
            ],
        ),
    ]
