/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/dashboard/Account.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Card_crafter: typeof import('./src/components/reference/card_crafter.vue')['default']
    Child1: typeof import('./src/components/emitTest/Child1.vue')['default']
    Child2: typeof import('./src/components/emitTest/Child2.vue')['default']
    Dashboard: typeof import('./src/components/dashboard/Dashboard.vue')['default']
    DashboardOverview: typeof import('./src/components/dashboard/DashboardOverview.vue')['default']
    DeckEditor: typeof import('./src/components/dashboard/DeckEditor.vue')['default']
    Display: typeof import('./src/components/dashboard/Display.vue')['default']
    Email_Verification: typeof import('./src/components/email_verification/Email_Verification.vue')['default']
    EmitTest: typeof import('./src/components/EmitTest.vue')['default']
    EmitTestTS: typeof import('./src/components/EmitTestTS.vue')['default']
    Feedback: typeof import('./src/components/dashboard/Feedback.vue')['default']
    FileInput: typeof import('./src/components/image_manager/FileInput.vue')['default']
    FileSelect: typeof import('./src/components/image_manager/FileSelect.vue')['default']
    FirstComponent: typeof import('./src/components/emitTest/FirstComponent.vue')['default']
    GlobalNavigation: typeof import('./src/components/navigation/GlobalNavigation.vue')['default']
    Help: typeof import('./src/components/dashboard/Help.vue')['default']
    ImageManager: typeof import('./src/components/image_manager/ImageManager.vue')['default']
    LoginForm: typeof import('./src/components/registration/LoginForm.vue')['default']
    Navbar: typeof import('./src/components/navigation/Navbar.vue')['default']
    NavbarSimple: typeof import('./src/components/navigation/NavbarSimple.vue')['default']
    Password_Reset: typeof import('./src/components/password_reset/Password_Reset.vue')['default']
    PhotoGallery: typeof import('./src/components/gallery/PhotoGallery.vue')['default']
    Player_Old: typeof import('./src/components/dashboard/Player_Old.vue')['default']
    PlayerInfo: typeof import('./src/components/dashboard/PlayerInfo.vue')['default']
    Profile: typeof import('./src/components/dashboard/Profile.vue')['default']
    Profile_Setup: typeof import('./src/components/profile_setup/Profile_Setup.vue')['default']
    Registration: typeof import('./src/components/registration/Registration.vue')['default']
    RegistrationForm: typeof import('./src/components/registration/RegistrationForm.vue')['default']
    ResetRequestForm: typeof import('./src/components/registration/ResetRequestForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondComponent: typeof import('./src/components/emitTest/SecondComponent.vue')['default']
    Settings: typeof import('./src/components/dashboard/Settings.vue')['default']
    Support: typeof import('./src/components/dashboard/Support.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
