/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/demo/csv_import': RouteRecordInfo<'/demo/csv_import', '/demo/csv_import', Record<never, never>, Record<never, never>>,
    '/demo/file_tree': RouteRecordInfo<'/demo/file_tree', '/demo/file_tree', Record<never, never>, Record<never, never>>,
    '/demo/image_manager': RouteRecordInfo<'/demo/image_manager', '/demo/image_manager', Record<never, never>, Record<never, never>>,
    '/demo/meme_maker': RouteRecordInfo<'/demo/meme_maker', '/demo/meme_maker', Record<never, never>, Record<never, never>>,
    '/demo/news_feed': RouteRecordInfo<'/demo/news_feed', '/demo/news_feed', Record<never, never>, Record<never, never>>,
    '/FakePage': RouteRecordInfo<'/FakePage', '/FakePage', Record<never, never>, Record<never, never>>,
    '/GenericPage': RouteRecordInfo<'/GenericPage', '/GenericPage', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
  }
}
